version: '2.27'

services:
  mysqldb:
    image: mysql:latest
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: mysqldb
      MYSQL_DATABASE: businessBox
    restart: always
    volumes:
      - mysqldb-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app_network

  tomcat:
    build: .
    container_name: tomcat
    depends_on:
      - mysqldb
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - ./volumes/tomcat-logs:/tmp
    networks:
      - app_network

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./deploy/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./business-box-angular/browser:/usr/share/nginx/html
      - ./volumes/nginx-logs:/var/log/nginx
    networks:
      - app_network

volumes:
  mysqldb-data:
  tomcat-logs:
  nginx-logs:

networks:
  app_network:
    driver: bridge